### ISSUE TITLE
is_prm missing definition (PR #1182)

### ISSUE THREAD

**Issue by muhammad-asad-confiz** [oneops/circuit-oneops-1#1183]
The deployment has failed. `is_prm` method is undefined.

 Following are the deployment logs:
```
 ================================================================================[0m
[31mRecipe Compile Error in /opt/oneops/inductor/circuit-oneops-1/components/cookbooks/azure_base/libraries/availability_set_manager.rb[0m
================================================================================[0m
[0mNameError[0m
---------------[0m
[0mCookbook Trace:[0m
undefined method `is_prm' for module `Utils'[0m
[0m /opt/oneops/inductor/circuit-oneops-1/components/cookbooks/azure_base/libraries/utils.rb:149:in `<module:Utils>'
---------[0m
/opt/oneops/inductor/circuit-oneops-1/components/cookbooks/azure_base/libraries/utils.rb:149:in `module_function'
[0m /opt/oneops/inductor/circuit-oneops-1/components/cookbooks/azure_base/libraries/availability_set_manager.rb:1:in `<top (required)>'[0m
[0m /opt/oneops/inductor/circuit-oneops-1/components/cookbooks/azure_base/libraries/resource_group_manager.rb:3:in `<top (required)>'
[0m /opt/oneops/inductor/circuit-oneops-1/components/cookbooks/azure_base/libraries/utils.rb:4:in `<top (required)>'
[0mRelevant File Content:[0m
[0m
/opt/oneops/inductor/circuit-oneops-1/components/cookbooks/azure_base/libraries/utils.rb
```
I believe the line [#155](https://github.com/oneops/circuit-oneops-1/pull/1182/files#diff-41780316d2ecd4512bd784c41c35b9ceR155) in `utils.rb` is cause the problem.

**Comment by muhammad-asad-confiz** [comment]
@dschelchkov 
This needs your attention.
