### ISSUE TITLE
compute failed issue in oneops

### ISSUE THREAD

**Issue by sanjeevkatthi** [oneops/circuit-oneops-1#682]
Hi,
I am facing an issue with compute in case of aws. The compute is failing without any faults.
The inductor log shows the below.

**2017-02-09 18:17:21,406	 INFO	ProcessRunner:68	4126:136373 - cmd out: [2017-02-09T18:17:21+00:00] DEBUG: filtered backtrace of compile error: /opt/oneops/inductor/circuit-oneops-1/components/cookbooks/compute/recipes/add_node_ec2.rb:153:in `exit',/opt/oneops/inductor/circuit-oneops-1/components/cookbooks/compute/recipes/add_node_ec2.rb:153:in `rescue in from_file',/opt/oneops/inductor/circuit-oneops-1/components/cookbooks/compute/recipes/add_node_ec2.rb:122:in `from_file',/opt/oneops/inductor/circuit-oneops-1/components/cookbooks/compute/recipes/add.rb:38:in `from_file'
2017-02-09 18:17:21,406	 INFO	ProcessRunner:68	4126:136373 - cmd out: [2017-02-09T18:17:21+00:00] DEBUG: filtered backtrace of compile error: /opt/oneops/inductor/circuit-oneops-1/components/cookbooks/compute/recipes/add_node_ec2.rb:153:in `exit',/opt/oneops/inductor/circuit-oneops-1/components/cookbooks/compute/recipes/add_node_ec2.rb:153:in `rescue in from_file',/opt/oneops/inductor/circuit-oneops-1/components/cookbooks/compute/recipes/add_node_ec2.rb:122:in `from_file',/opt/oneops/inductor/circuit-oneops-1/components/cookbooks/compute/recipes/add.rb:38:in `from_file'
2017-02-09 18:17:21,406	 INFO	ProcessRunner:68	4126:136373 - cmd out: [2017-02-09T18:17:21+00:00] DEBUG: backtrace entry for compile error: '/opt/oneops/inductor/circuit-oneops-1/components/cookbooks/compute/recipes/add_node_ec2.rb:153:in `exit''
2017-02-09 18:17:21,406	 INFO	ProcessRunner:68	4126:136373 - cmd out: [2017-02-09T18:17:21+00:00] DEBUG: Line number of compile error: '153'
2017-02-09 18:17:21,587	 INFO	ProcessRunner:68	4126:136373 - cmd out: 
2017-02-09 18:17:21,587	 INFO	ProcessRunner:68	4126:136373 - cmd out: ================================================================================
2017-02-09 18:17:21,587	 INFO	ProcessRunner:68	4126:136373 - cmd out: Recipe Compile Error in /opt/oneops/inductor/circuit-oneops-1/components/cookbooks/compute/recipes/add.rb
2017-02-09 18:17:21,587	 INFO	ProcessRunner:68	4126:136373 - cmd out: ================================================================================
2017-02-09 18:17:21,587	 INFO	ProcessRunner:68	4126:136373 - cmd out: 
2017-02-09 18:17:21,587	 INFO	ProcessRunner:68	4126:136373 - cmd out: SystemExit
2017-02-09 18:17:21,587	 INFO	ProcessRunner:68	4126:136373 - cmd out: ----------
2017-02-09 18:17:21,587	 INFO	ProcessRunner:68	4126:136373 - cmd out: exit**

Please help in resolving this issue.

**Comment by vasumathialagan** [comment]
Is this Resolved?
