### ISSUE TITLE
(Gem::LoadError)_Issue while running circuit install

### ISSUE THREAD

**Issue by shivav2025** [oneops/circuit-oneops-1#744]
shiva@shiva-VirtualBox:~/install/inductor/circuit-oneops-1$ circuit install
Expected string default value for '--force'; got true (boolean)
Expected string default value for '--force'; got true (boolean)
     running   knife model sync -a 
/var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:40:in `block in setup': You have already activated ffi-yajl 2.3.0, but your Gemfile requires ffi-yajl 1.4.0. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
	from /var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:25:in `map'
	from /var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:25:in `setup'
	from /var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler.rb:100:in `setup'
	from /var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/setup.rb:10:in `<top (required)>'
	from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/oneops-admin-1.0.0/lib/chef/knife/register.rb:10:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/chef-12.19.36/lib/chef/knife/core/subcommand_loader.rb:100:in `load'
	from /var/lib/gems/2.3.0/gems/chef-12.19.36/lib/chef/knife/core/subcommand_loader.rb:100:in `block in load_commands'
	from /var/lib/gems/2.3.0/gems/chef-12.19.36/lib/chef/knife/core/subcommand_loader.rb:100:in `each'
	from /var/lib/gems/2.3.0/gems/chef-12.19.36/lib/chef/knife/core/subcommand_loader.rb:100:in `load_commands'
	from /var/lib/gems/2.3.0/gems/chef-12.19.36/lib/chef/knife/core/subcommand_loader.rb:110:in `load_command'
	from /var/lib/gems/2.3.0/gems/chef-12.19.36/lib/chef/knife/core/subcommand_loader.rb:124:in `command_class_from'
	from /var/lib/gems/2.3.0/gems/chef-12.19.36/lib/chef/knife.rb:153:in `subcommand_class_from'
	from /var/lib/gems/2.3.0/gems/chef-12.19.36/lib/chef/knife.rb:214:in `run'
	from /var/lib/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/knife.rb:156:in `run'
	from /var/lib/gems/2.3.0/gems/chef-12.19.36/bin/knife:25:in `<top (required)>'
	from /usr/local/bin/knife:22:in `load'
	from /usr/local/bin/knife:22:in `<main>'
fail.  knife model sync -a  returned: 1

**Comment by shivav2025** [comment]
I solved this issue. I have given wrong certificate in the inductor's vmargs file.

~/install/inductor/clouds-enabled/public.oneops.clouds.google/conf/vmargs
