### ISSUE TITLE
OneOps: Chef-Knife error: fail. knife pack sync -a returned: 100

### ISSUE THREAD

**Issue by yrmallu** [oneops/circuit-oneops-1#870]
While I’m running cookbooks I’m getting the following error for chef

Error:
Pack activemq version 1 matches signature b759f6d1947dc07a02bbc17182e40b06, use --reload to force load.
source: /public/oneops/packs
WARNING: Pack ansible version 1 signature is different from file signature 278e9843f961dc65c2652939e44e0274
Uploading pack ansible
Updating pack ansible
Updating pack ansible version 1
Successfuly saved pack ansible version 1
============> Platform
Creating resource ansible for ansible
ERROR: knife encountered an unexpected error
This may be a bug in the 'pack sync' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NoMethodError: undefined method `comments=' for false:FalseClass
fail. knife pack sync -a returned: 100
install inductor as ooadmin
Expected string default value for '--force'; got true (boolean)
Expected string default value for '--force'; got true (boolean)

I have traced the error so it’s showing 
Knife status –VV

WARN: Unresolved specs during Gem::Specification.reset:
      net-ssh (>= 2.6.5, ~> 2.6)
      rack (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
WARN: Failed to read the private key /opt/oneops/circuit-oneops-1/.chef/client_key.pem: #<Errno::ENOENT: No such file or directory - /opt/oneops/circuit-oneops-1/.chef/client_key.pem>
/usr/local/share/gems/gems/chef-11.18.12/lib/chef/http/authenticator.rb:78:in `rescue in load_signing_key': I cannot read /opt/oneops/circuit-oneops-1/.chef/client_key.pem, which you told me to use to sign requests! (Chef::Exceptions::PrivateKeyMissing)
        from /usr/local/share/gems/gems/chef-11.18.12/lib/chef/http/authenticator.rb:68:in `load_signing_key'
        from /usr/local/share/gems/gems/chef-11.18.12/lib/chef/http/authenticator.rb:38:in `initialize'

I don’t have client_key.pem file validator.pem file

Which is mentioned in kinife.rb file

https://github.com/oneops/circuit-oneops-1/blob/master/.chef/knife.rb

i.e.,
log_level :info
	log_location STDOUT
	print_after true
	admin false
	node_name 'oneops'
	register 'oneops'
	version '1.0.0'
	nspath '/public'
	useversion 'true'
	client_key 'client_key.pem'
	validation_client_name 'chef-validator'
	validation_key 'validation.pem'
	chef_server_url 'http://localhost:4000'
	cache_type 'BasicFile'
	cache_options( :path => '.chef/checksums' )
	cookbook_path [ 'components/cookbooks' ]
	publish_path 'pkgs'
	pack_path [ 'packs' ]
	service_path [ 'services' ]
	cloud_path [ 'clouds' ]
	catalog_path [ 'catalogs' ]
	default_impl 'oo::chef-11.18.12'
	

Please let me know how to fix the issue.

**Comment by yrmallu** [comment]
@dschelchkov can you please help me to fix this issue

**Comment by facewy** [comment]
same issue to me.
